version: '3.8'

services:
  # Weather Monitoring Service
  weather-service:
    build:
      context: ./weather-service
    ports:
      - "8081:8080"
    networks:
      - marsy-net

  rocket-service:
    build:
      context: ./rocket-service
    ports:
      - "8082:8080"
    networks:
      - marsy-net

  command-service:
    build:
      context: ./command-service
    ports:
      - "8083:8080"
    networks:
      - marsy-net

  launchpad-service:
    build:
      context: ./launchpad-service
    ports:
      - "8084:8080"
    networks:
      - marsy-net

networks:
  marsy-net:
    driver: bridge

