version: '3.8'

services:
  # Weather Monitoring Service
  weather-service:
    container_name: weather-service
    build:
      context: ./weather-service
    ports:
      - "8081:8080"
    networks:
      - marsy-net

  rocket-service:
    container_name: rocket-service
    build:
      context: ./rocket-service
    ports:
      - "8082:8080"
    networks:
      - marsy-net

  command-service:
    container_name: command-service
    build:
      context: ./command-service
    ports:
      - "8083:8080"
    networks:
      - marsy-net

  launchpad-service:
    container_name: launchpad-service
    build:
      context: ./launchpad-service
    ports:
      - "8084:8080"
    networks:
      - marsy-net

  payload-service:
    container_name: payload-service
    build:
      context: ./payload-service
    ports:
      - "8085:8080"
    networks:
      - marsy-net

  telemetry-service:
    container_name: telemetry-service
    build:
      context: ./telemetry-service
    ports:
      - "8086:8080"
    networks:
      - marsy-net

  staging-service:
    container_name: staging-service
    build:
      context: ./staging-service
    ports:
      - "8087:8080"
    networks:
      - marsy-net

  satellite-service:
    container_name: satellite-service
    build:
      context: ./satellite-service
    ports:
      - "8088:8080"
    networks:
      - marsy-net

  booster-service:
    container_name: booster-service
    build:
      context: ./booster-service
    ports:
      - "8089:8080"
    networks:
      - marsy-net

networks:
  marsy-net:
    driver: bridge

