name: CI

on: [ push, pull_request ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Giving permissions
        run: chmod +x prepare.sh test.sh

      - name: Prepare services
        run: bash prepare.sh

      - name: Run tests
        run: bash test.sh
