name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Stop and remove all Docker containers
        run: |
          docker stop $(docker ps -aq) || true
          docker rm $(docker ps -aq) || true

      - name: Prepare services
        run: bash prepare.sh

      - name: Run tests
        run: bash test.sh

      - name: Cleanup Docker resources
        if: always()
        run: |
          docker system prune --force --all --volumes
          docker volume prune --force
          docker network prune --force
